config/routes.rb
Rails.application.routes.draw do
  post "/shingles/page_favorited", :to => "home#page_favorited", :as => :page_favorited
  post "/shingles/page_unfavorited", :to => "home#page_unfavorited", :as => :page_unfavorited
  post "/shingles/zip_updated", :to => "home#zip_updated", :as => :shingle_zip_updated
  get "/shingles/(:shingle)/(:color)", :to => "home#shingles", :as => :shingles
  get "/shingles_by_zip/:zip/(:shingle)/(:color)", :to => "home#shingles", :as => :shingles_by_zip

  namespace :admin do
    get "/reporting/shingles/all_favorites", :to => "reporting#all_favorites", :as => :shingles_all_favorites
    get "/reporting/shingles/favorite_totals", :to => "reporting#favorite_totals", :as => :shingles_favorite_totals
    get "/reporting", :to => "reporting#index", :as => :reporting
    post "/log_in", :to => "reporting#log_in", :as => :reporting_login
    get "/log_out", :to => "reporting#log_out", :as => :reporting_logout

    root :to => "reporting#index"
  end

  root :to => "home#shingles"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :ip, :presence => true
  validates :url, :presence => true, :uniqueness => {:scope => :ip}
  validates :shingle, :uniqueness => {:scope => [:ip, :color]}

  # Options are
  def self.add(url, ip, options = {})
    begin
      create!(options.merge(:url => url, :ip => ip))
    rescue => e
      if !e.message.match?("has already been taken")
        raise e
      end
    end
  end
end

app/models/zip.rb
class Zip < ApplicationRecord
  self.primary_key = "code"
  validates :code, :presence => true, :uniqueness => true, :case_sensitive => false
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    before_action :user_logged_in?

    def current_user
      @__current_user ||= session[:current_user]
    end

    helper_method :current_user

    def current_user?
      current_user.present?
    end

    helper_method :current_user?

    def user_logged_in?
      if !current_user.present?
        redirect_to admin_root_path
      end
    end

    def log_user_out
      @__current_user = nil
      session[:current_user] = nil
    end

    def log_user_in(user_id, password)
      if user_id == "admin" && password == "nimda"
        session[:current_user] = true
      else
        raise "Username and Password not recognized."
      end
    end
  end
end

app/controllers/admin/reporting_controller.rb
module Admin
  class ReportingController < AdminController
    skip_before_action :user_logged_in?,  :only => [:index, :log_in]

    def index

    end

    def log_in
      log_user_in(params[:user_name], params[:password])

      redirect_to admin_reporting_path
    end

    def log_out
      log_user_out

      redirect_to admin_reporting_path
    end

    def all_favorites
      @favorites = Favorite.order(:created_at => :desc).all
    end

    def favorite_totals
      @favorites = Favorite.order(:shingle, :color).group(:shingle, :color).count
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require "shingle_connection"

class HomeController < ApplicationController
  def shingles
    if params[:zip].blank?
      flash.now[:notice] = "Please enter a zip code to show available shingles in your area."
    end

    @current_zip = Zip.find("43659")
    default_zip = @current_zip

    @favorited = Favorite.exists?(:url => request.path, :ip => request.ip)

    begin
      if params[:zip].present?
        @current_zip = Zip.find(params[:zip])
      end
    rescue => e
      @current_zip = default_zip
      flash.now[:error] = "Zip code not found. (#{e})"
    end

    @shingles = ShingleConnection.shingles(:zip => @current_zip.code)

    @current_shingle = params["shingle"].present? ? @shingles.find { |shingle| shingle["uid"] == params["shingle"] } : @shingles.first
    @current_color = @current_shingle["shingle_colors"].find { |color| color["uid"] == params["color"] } || @current_shingle["shingle_colors"].first
  end

  def zip_updated
    if params[:zip].present?
      redirect_to(shingles_by_zip_path(params[:zip], params[:shingle], params[:color]))
    else
      redirect_to(shingles_path(params[:shingle], params[:color]))
    end
  end

  def page_favorited
    Favorite.add(params[:url], request.ip, :color => params[:color], :shingle => params[:shingle])
    Rails.logger.info("#{params[:url]} favorited.")

    render :plain => "OK"
  end

  def page_unfavorited
    Favorite.find_by(:url => params[:url], :ip => request.ip, :color => params[:color], :shingle => params[:shingle]).destroy
    Rails.logger.info("#{params[:url]} unfavorited.")

    render :plain => "OK"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/reporting/all_favorites.haml
%table
  %tr
    %th ID
    %th URL
    %th IP
    %th Shingle
    %th Color
  - @favorites.each do |fave|
    %tr{:id => "favorite_#{fave.id}"}
      %td= fave.id
      %td= fave.url
      %td= fave.ip
      %td= fave.shingle
      %td= fave.color

app/views/admin/reporting/favorite_totals.haml
%table
  %tr
    %th Shingle
    %th Color
    %th Count
  - @favorites.each do |fave|
    %tr{:id => "favorite_#{fave[0][0]}_#{fave[0][1]}"}
      %td= fave[0][0] || "Nil"
      %td= fave[0][1] || "Nil"
      %td= fave[1]

app/views/admin/reporting/index.haml
%h1 Owens Corning Developer Test Admin Portal

- if current_user?
  %h3 Activities
  %ul
    %li= link_to("All Favorite Entries", admin_shingles_all_favorites_path)
    %li= link_to("All Favorite Totals", admin_shingles_favorite_totals_path)
    %li= link_to("Log Out", admin_reporting_logout_path)
- else
  = form_tag admin_reporting_login_path, :id => "log-in-form" do
    %fieldset
      User Name
      = text_field_tag(:user_name, @user_name)
    %fieldset
      Password
      = password_field_tag(:password)
    %span Hint:  User name is 'admin'.  The password is just the opposite. </br>
    = submit_tag("Log In")

app/views/home/shingles.haml
- main_image_key = "house_thumb_image_url"
- shingle_colors = ShingleConnection.shingle_colors(@current_shingle)

#shingle-name
  = @current_shingle["proper_name"]

#main-image-container
  #main-image
    = image_tag(@current_color[main_image_key], :id => "main-image-tag")

  #shingle-selector
    Select Shingle for Preview
    = select_tag("shingle-names", options_for_select(@shingles.collect{|shingle| [shingle["proper_name"], shingle["uid"]]}, :selected => @current_shingle["uid"]))

  #zip-selector
    Enter Zip Code for Availability in Your Area
    = form_tag(shingle_zip_updated_path) do
      = text_field_tag(:zip, @current_zip.code)           
      = hidden_field_tag(:shingle, @current_shingle["uid"])
      = hidden_field_tag(:color, @current_color["uid"])
      = submit_tag("Set Zip Code")
  
  #utilities
    = mail_to nil, "Mail this page to a friend.", :body => request.original_url, :subject => "Check Out These Shingles!"
    #favorite-links              
      = hidden_field_tag("favorited", @favorited)
      %div{:id => "favorite-link"}
        <a href="">Like this Page</a>             
      %div{:id => "unfavorite-link"}
        <a href="">Unlike this Page</a>             
    

#swatches
  - shingle_colors.each do |color|
    .color-swatch{:class => (color["name"] == @current_color["name"] ? :selected : nil), "data-large-image-url" => color[main_image_key]}
      = image_tag(color["swatch_160x160_url"], "data-color-id" => color["uid"], :alt => color["name"])
      .color-name= color["name"]

= hidden_field_tag("shingle-uid-tag", @current_shingle["uid"])
= hidden_field_tag("color-uid-tag", @current_color["uid"])

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Owens Corning Developer Test
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    - if flash.any?
      - flash.keys.each do |key|
        .flash-message{:class => key}
          %div
            = flash[key]
    = yield